/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'younglee' at '3/2/17 3:19 PM' with Gradle 2.14.1
 *
 * @author younglee, @date 3/2/17 3:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
